// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ChangeHpReason.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Lemonade.Net.Protocol {

  /// <summary>Holder for reflection information generated from ChangeHpReason.proto</summary>
  public static partial class ChangeHpReasonReflection {

    #region Descriptor
    /// <summary>File descriptor for ChangeHpReason.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ChangeHpReasonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRDaGFuZ2VIcFJlYXNvbi5wcm90byrjBAoOQ2hhbmdlSHBSZWFzb24SEAoM",
            "Q2hhbmdlSHBOb25lEAASFQoRQ2hhbmdlSHBTdWJBdmF0YXIQARIWChJDaGFu",
            "Z2VIcFN1Yk1vbnN0ZXIQAhITCg9DaGFuZ2VIcFN1YkdlYXIQAxIUChBDaGFu",
            "Z2VIcFN1YkVudmlyEAQSEwoPQ2hhbmdlSHBTdWJGYWxsEAUSFAoQQ2hhbmdl",
            "SHBTdWJEcmF3bhAGEhQKEENoYW5nZUhwU3ViQWJ5c3MQBxIWChJDaGFuZ2VI",
            "cFN1YkFiaWxpdHkQCBIVChFDaGFuZ2VIcFN1YlN1bW1vbhAJEhUKEUNoYW5n",
            "ZUhwU3ViU2NyaXB0EAoSEQoNQ2hhbmdlSHBTdWJHbRALEhcKE0NoYW5nZUhw",
            "U3ViS2lsbFNlbGYQDBIaChZDaGFuZ2VIcFN1YkNsaW1hdGVDb2xkEA0SHQoZ",
            "Q2hhbmdlSHBTdWJTdG9ybUxpZ2h0bmluZxAOEh8KG0NoYW5nZUhwU3ViS2ls",
            "bFNlcnZlckdhZGdldBAPEhEKDUNoYW5nZUhwQnlMdWEQMxIWChJDaGFuZ2VI",
            "cEFkZEFiaWxpdHkQZRITCg9DaGFuZ2VIcEFkZEl0ZW0QZhIVChFDaGFuZ2VI",
            "cEFkZFJldml2ZRBnEhYKEkNoYW5nZUhwQWRkVXBncmFkZRBoEhUKEUNoYW5n",
            "ZUhwQWRkU3RhdHVlEGkSGQoVQ2hhbmdlSHBBZGRCYWNrZ3JvdW5kEGoSEQoN",
            "Q2hhbmdlSHBBZGRHbRBrEiIKHkNoYW5nZUhwQWRkVHJpYWxBdmF0YXJBY3Rp",
            "dml0eRBsQhiqAhVMZW1vbmFkZS5OZXQuUHJvdG9jb2xiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Lemonade.Net.Protocol.ChangeHpReason), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ChangeHpReason {
    [pbr::OriginalName("ChangeHpNone")] ChangeHpNone = 0,
    [pbr::OriginalName("ChangeHpSubAvatar")] ChangeHpSubAvatar = 1,
    [pbr::OriginalName("ChangeHpSubMonster")] ChangeHpSubMonster = 2,
    [pbr::OriginalName("ChangeHpSubGear")] ChangeHpSubGear = 3,
    [pbr::OriginalName("ChangeHpSubEnvir")] ChangeHpSubEnvir = 4,
    [pbr::OriginalName("ChangeHpSubFall")] ChangeHpSubFall = 5,
    [pbr::OriginalName("ChangeHpSubDrawn")] ChangeHpSubDrawn = 6,
    [pbr::OriginalName("ChangeHpSubAbyss")] ChangeHpSubAbyss = 7,
    [pbr::OriginalName("ChangeHpSubAbility")] ChangeHpSubAbility = 8,
    [pbr::OriginalName("ChangeHpSubSummon")] ChangeHpSubSummon = 9,
    [pbr::OriginalName("ChangeHpSubScript")] ChangeHpSubScript = 10,
    [pbr::OriginalName("ChangeHpSubGm")] ChangeHpSubGm = 11,
    [pbr::OriginalName("ChangeHpSubKillSelf")] ChangeHpSubKillSelf = 12,
    [pbr::OriginalName("ChangeHpSubClimateCold")] ChangeHpSubClimateCold = 13,
    [pbr::OriginalName("ChangeHpSubStormLightning")] ChangeHpSubStormLightning = 14,
    [pbr::OriginalName("ChangeHpSubKillServerGadget")] ChangeHpSubKillServerGadget = 15,
    [pbr::OriginalName("ChangeHpByLua")] ChangeHpByLua = 51,
    [pbr::OriginalName("ChangeHpAddAbility")] ChangeHpAddAbility = 101,
    [pbr::OriginalName("ChangeHpAddItem")] ChangeHpAddItem = 102,
    [pbr::OriginalName("ChangeHpAddRevive")] ChangeHpAddRevive = 103,
    [pbr::OriginalName("ChangeHpAddUpgrade")] ChangeHpAddUpgrade = 104,
    [pbr::OriginalName("ChangeHpAddStatue")] ChangeHpAddStatue = 105,
    [pbr::OriginalName("ChangeHpAddBackground")] ChangeHpAddBackground = 106,
    [pbr::OriginalName("ChangeHpAddGm")] ChangeHpAddGm = 107,
    [pbr::OriginalName("ChangeHpAddTrialAvatarActivity")] ChangeHpAddTrialAvatarActivity = 108,
  }

  #endregion

}

#endregion Designer generated code
