// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: EntityAuthorityInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Lemonade.Net.Protocol {

  /// <summary>Holder for reflection information generated from EntityAuthorityInfo.proto</summary>
  public static partial class EntityAuthorityInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for EntityAuthorityInfo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EntityAuthorityInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlFbnRpdHlBdXRob3JpdHlJbmZvLnByb3RvGhpBYmlsaXR5U3luY1N0YXRl",
            "SW5mby5wcm90bxofRW50aXR5UmVuZGVyZXJDaGFuZ2VkSW5mby5wcm90bxoX",
            "U2NlbmVFbnRpdHlBaUluZm8ucHJvdG8aDFZlY3Rvci5wcm90bxokQW5pbWF0",
            "b3JQYXJhbWV0ZXJWYWx1ZUluZm9QYWlyLnByb3RvIvYBChNFbnRpdHlBdXRo",
            "b3JpdHlJbmZvEisKDGFiaWxpdHlfaW5mbxgBIAEoCzIVLkFiaWxpdHlTeW5j",
            "U3RhdGVJbmZvEjkKFXJlbmRlcmVyX2NoYW5nZWRfaW5mbxgCIAEoCzIaLkVu",
            "dGl0eVJlbmRlcmVyQ2hhbmdlZEluZm8SIwoHYWlfaW5mbxgDIAEoCzISLlNj",
            "ZW5lRW50aXR5QWlJbmZvEhkKCGJvcm5fcG9zGAQgASgLMgcuVmVjdG9yEjcK",
            "DnBvc2VfcGFyYV9saXN0GAUgAygLMh8uQW5pbWF0b3JQYXJhbWV0ZXJWYWx1",
            "ZUluZm9QYWlyQhiqAhVMZW1vbmFkZS5OZXQuUHJvdG9jb2xiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Lemonade.Net.Protocol.AbilitySyncStateInfoReflection.Descriptor, global::Lemonade.Net.Protocol.EntityRendererChangedInfoReflection.Descriptor, global::Lemonade.Net.Protocol.SceneEntityAiInfoReflection.Descriptor, global::Lemonade.Net.Protocol.VectorReflection.Descriptor, global::Lemonade.Net.Protocol.AnimatorParameterValueInfoPairReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Lemonade.Net.Protocol.EntityAuthorityInfo), global::Lemonade.Net.Protocol.EntityAuthorityInfo.Parser, new[]{ "AbilityInfo", "RendererChangedInfo", "AiInfo", "BornPos", "PoseParaList" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class EntityAuthorityInfo : pb::IMessage<EntityAuthorityInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EntityAuthorityInfo> _parser = new pb::MessageParser<EntityAuthorityInfo>(() => new EntityAuthorityInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EntityAuthorityInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Lemonade.Net.Protocol.EntityAuthorityInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityAuthorityInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityAuthorityInfo(EntityAuthorityInfo other) : this() {
      abilityInfo_ = other.abilityInfo_ != null ? other.abilityInfo_.Clone() : null;
      rendererChangedInfo_ = other.rendererChangedInfo_ != null ? other.rendererChangedInfo_.Clone() : null;
      aiInfo_ = other.aiInfo_ != null ? other.aiInfo_.Clone() : null;
      bornPos_ = other.bornPos_ != null ? other.bornPos_.Clone() : null;
      poseParaList_ = other.poseParaList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityAuthorityInfo Clone() {
      return new EntityAuthorityInfo(this);
    }

    /// <summary>Field number for the "ability_info" field.</summary>
    public const int AbilityInfoFieldNumber = 1;
    private global::Lemonade.Net.Protocol.AbilitySyncStateInfo abilityInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Lemonade.Net.Protocol.AbilitySyncStateInfo AbilityInfo {
      get { return abilityInfo_; }
      set {
        abilityInfo_ = value;
      }
    }

    /// <summary>Field number for the "renderer_changed_info" field.</summary>
    public const int RendererChangedInfoFieldNumber = 2;
    private global::Lemonade.Net.Protocol.EntityRendererChangedInfo rendererChangedInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Lemonade.Net.Protocol.EntityRendererChangedInfo RendererChangedInfo {
      get { return rendererChangedInfo_; }
      set {
        rendererChangedInfo_ = value;
      }
    }

    /// <summary>Field number for the "ai_info" field.</summary>
    public const int AiInfoFieldNumber = 3;
    private global::Lemonade.Net.Protocol.SceneEntityAiInfo aiInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Lemonade.Net.Protocol.SceneEntityAiInfo AiInfo {
      get { return aiInfo_; }
      set {
        aiInfo_ = value;
      }
    }

    /// <summary>Field number for the "born_pos" field.</summary>
    public const int BornPosFieldNumber = 4;
    private global::Lemonade.Net.Protocol.Vector bornPos_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Lemonade.Net.Protocol.Vector BornPos {
      get { return bornPos_; }
      set {
        bornPos_ = value;
      }
    }

    /// <summary>Field number for the "pose_para_list" field.</summary>
    public const int PoseParaListFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Lemonade.Net.Protocol.AnimatorParameterValueInfoPair> _repeated_poseParaList_codec
        = pb::FieldCodec.ForMessage(42, global::Lemonade.Net.Protocol.AnimatorParameterValueInfoPair.Parser);
    private readonly pbc::RepeatedField<global::Lemonade.Net.Protocol.AnimatorParameterValueInfoPair> poseParaList_ = new pbc::RepeatedField<global::Lemonade.Net.Protocol.AnimatorParameterValueInfoPair>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Lemonade.Net.Protocol.AnimatorParameterValueInfoPair> PoseParaList {
      get { return poseParaList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EntityAuthorityInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EntityAuthorityInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(AbilityInfo, other.AbilityInfo)) return false;
      if (!object.Equals(RendererChangedInfo, other.RendererChangedInfo)) return false;
      if (!object.Equals(AiInfo, other.AiInfo)) return false;
      if (!object.Equals(BornPos, other.BornPos)) return false;
      if(!poseParaList_.Equals(other.poseParaList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (abilityInfo_ != null) hash ^= AbilityInfo.GetHashCode();
      if (rendererChangedInfo_ != null) hash ^= RendererChangedInfo.GetHashCode();
      if (aiInfo_ != null) hash ^= AiInfo.GetHashCode();
      if (bornPos_ != null) hash ^= BornPos.GetHashCode();
      hash ^= poseParaList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (abilityInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AbilityInfo);
      }
      if (rendererChangedInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(RendererChangedInfo);
      }
      if (aiInfo_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(AiInfo);
      }
      if (bornPos_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(BornPos);
      }
      poseParaList_.WriteTo(output, _repeated_poseParaList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (abilityInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AbilityInfo);
      }
      if (rendererChangedInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(RendererChangedInfo);
      }
      if (aiInfo_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(AiInfo);
      }
      if (bornPos_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(BornPos);
      }
      poseParaList_.WriteTo(ref output, _repeated_poseParaList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (abilityInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AbilityInfo);
      }
      if (rendererChangedInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RendererChangedInfo);
      }
      if (aiInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AiInfo);
      }
      if (bornPos_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BornPos);
      }
      size += poseParaList_.CalculateSize(_repeated_poseParaList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EntityAuthorityInfo other) {
      if (other == null) {
        return;
      }
      if (other.abilityInfo_ != null) {
        if (abilityInfo_ == null) {
          AbilityInfo = new global::Lemonade.Net.Protocol.AbilitySyncStateInfo();
        }
        AbilityInfo.MergeFrom(other.AbilityInfo);
      }
      if (other.rendererChangedInfo_ != null) {
        if (rendererChangedInfo_ == null) {
          RendererChangedInfo = new global::Lemonade.Net.Protocol.EntityRendererChangedInfo();
        }
        RendererChangedInfo.MergeFrom(other.RendererChangedInfo);
      }
      if (other.aiInfo_ != null) {
        if (aiInfo_ == null) {
          AiInfo = new global::Lemonade.Net.Protocol.SceneEntityAiInfo();
        }
        AiInfo.MergeFrom(other.AiInfo);
      }
      if (other.bornPos_ != null) {
        if (bornPos_ == null) {
          BornPos = new global::Lemonade.Net.Protocol.Vector();
        }
        BornPos.MergeFrom(other.BornPos);
      }
      poseParaList_.Add(other.poseParaList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (abilityInfo_ == null) {
              AbilityInfo = new global::Lemonade.Net.Protocol.AbilitySyncStateInfo();
            }
            input.ReadMessage(AbilityInfo);
            break;
          }
          case 18: {
            if (rendererChangedInfo_ == null) {
              RendererChangedInfo = new global::Lemonade.Net.Protocol.EntityRendererChangedInfo();
            }
            input.ReadMessage(RendererChangedInfo);
            break;
          }
          case 26: {
            if (aiInfo_ == null) {
              AiInfo = new global::Lemonade.Net.Protocol.SceneEntityAiInfo();
            }
            input.ReadMessage(AiInfo);
            break;
          }
          case 34: {
            if (bornPos_ == null) {
              BornPos = new global::Lemonade.Net.Protocol.Vector();
            }
            input.ReadMessage(BornPos);
            break;
          }
          case 42: {
            poseParaList_.AddEntriesFrom(input, _repeated_poseParaList_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (abilityInfo_ == null) {
              AbilityInfo = new global::Lemonade.Net.Protocol.AbilitySyncStateInfo();
            }
            input.ReadMessage(AbilityInfo);
            break;
          }
          case 18: {
            if (rendererChangedInfo_ == null) {
              RendererChangedInfo = new global::Lemonade.Net.Protocol.EntityRendererChangedInfo();
            }
            input.ReadMessage(RendererChangedInfo);
            break;
          }
          case 26: {
            if (aiInfo_ == null) {
              AiInfo = new global::Lemonade.Net.Protocol.SceneEntityAiInfo();
            }
            input.ReadMessage(AiInfo);
            break;
          }
          case 34: {
            if (bornPos_ == null) {
              BornPos = new global::Lemonade.Net.Protocol.Vector();
            }
            input.ReadMessage(BornPos);
            break;
          }
          case 42: {
            poseParaList_.AddEntriesFrom(ref input, _repeated_poseParaList_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
