// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ForwardType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Lemonade.Net.Protocol {

  /// <summary>Holder for reflection information generated from ForwardType.proto</summary>
  public static partial class ForwardTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for ForwardType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ForwardTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFGb3J3YXJkVHlwZS5wcm90byrrAQoLRm9yd2FyZFR5cGUSEQoNRk9SV0FS",
            "RF9MT0NBTBAAEhIKDkZPUldBUkRfVE9fQUxMEAESHQoZRk9SV0FSRF9UT19B",
            "TExfRVhDRVBUX0NVUhACEhMKD0ZPUldBUkRfVE9fSE9TVBADEhgKFEZPUldB",
            "UkRfVE9fQUxMX0dVRVNUEAQSEwoPRk9SV0FSRF9UT19QRUVSEAUSFAoQRk9S",
            "V0FSRF9UT19QRUVSUxAGEhcKE0ZPUldBUkRfT05MWV9TRVJWRVIQBxIjCh9G",
            "T1JXQVJEX1RPX0FMTF9FWElTVF9FWENFUFRfQ1VSEAhCGKoCFUxlbW9uYWRl",
            "Lk5ldC5Qcm90b2NvbGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Lemonade.Net.Protocol.ForwardType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ForwardType {
    [pbr::OriginalName("FORWARD_LOCAL")] ForwardLocal = 0,
    [pbr::OriginalName("FORWARD_TO_ALL")] ForwardToAll = 1,
    [pbr::OriginalName("FORWARD_TO_ALL_EXCEPT_CUR")] ForwardToAllExceptCur = 2,
    [pbr::OriginalName("FORWARD_TO_HOST")] ForwardToHost = 3,
    [pbr::OriginalName("FORWARD_TO_ALL_GUEST")] ForwardToAllGuest = 4,
    [pbr::OriginalName("FORWARD_TO_PEER")] ForwardToPeer = 5,
    [pbr::OriginalName("FORWARD_TO_PEERS")] ForwardToPeers = 6,
    [pbr::OriginalName("FORWARD_ONLY_SERVER")] ForwardOnlyServer = 7,
    [pbr::OriginalName("FORWARD_TO_ALL_EXIST_EXCEPT_CUR")] ForwardToAllExistExceptCur = 8,
  }

  #endregion

}

#endregion Designer generated code
