// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GachaInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Lemonade.Net.Protocol {

  /// <summary>Holder for reflection information generated from GachaInfo.proto</summary>
  public static partial class GachaInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for GachaInfo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GachaInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9HYWNoYUluZm8ucHJvdG8aEUdhY2hhVXBJbmZvLnByb3RvIv0DCglHYWNo",
            "YUluZm8SEQoJZ2FjaGFUeXBlGAEgASgNEhIKCnNjaGVkdWxlSWQYAiABKA0S",
            "EQoJYmVnaW5UaW1lGAMgASgNEg8KB2VuZFRpbWUYBCABKA0SEgoKY29zdEl0",
            "ZW1JZBgFIAEoDRITCgtjb3N0SXRlbU51bRgGIAEoDRIXCg9nYWNoYVByZWZh",
            "YlBhdGgYByABKAkSFAoMZ2FjaGFQcm9iVXJsGAggASgJEhYKDmdhY2hhUmVj",
            "b3JkVXJsGAkgASgJEh4KFmdhY2hhUHJldmlld1ByZWZhYlBhdGgYCiABKAkS",
            "FQoNdGVuQ29zdEl0ZW1JZBgLIAEoDRIWCg50ZW5Db3N0SXRlbU51bRgMIAEo",
            "DRIWCg5sZWZ0R2FjaGFUaW1lcxgNIAEoDRIXCg9nYWNoYVRpbWVzTGltaXQY",
            "DiABKA0SEwoLZ2FjaGFTb3J0SWQYDyABKA0SGwoTZ2FjaGFQcm9iVXJsT3Zl",
            "cnNlYRgQIAEoCRIdChVnYWNoYVJlY29yZFVybE92ZXJzZWEYESABKAkSJQoP",
            "Z2FjaGFVcEluZm9MaXN0GBIgAygLMgwuR2FjaGFVcEluZm8SFgoOZ2FjaGFU",
            "aXRsZVBhdGgYEyABKAkSEgoKbWFpbk5hbWVJZBgUIAMoDRIRCglzdWJOYW1l",
            "SWQYFSADKA1CGKoCFUxlbW9uYWRlLk5ldC5Qcm90b2NvbGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Lemonade.Net.Protocol.GachaUpInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Lemonade.Net.Protocol.GachaInfo), global::Lemonade.Net.Protocol.GachaInfo.Parser, new[]{ "GachaType", "ScheduleId", "BeginTime", "EndTime", "CostItemId", "CostItemNum", "GachaPrefabPath", "GachaProbUrl", "GachaRecordUrl", "GachaPreviewPrefabPath", "TenCostItemId", "TenCostItemNum", "LeftGachaTimes", "GachaTimesLimit", "GachaSortId", "GachaProbUrlOversea", "GachaRecordUrlOversea", "GachaUpInfoList", "GachaTitlePath", "MainNameId", "SubNameId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GachaInfo : pb::IMessage<GachaInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GachaInfo> _parser = new pb::MessageParser<GachaInfo>(() => new GachaInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GachaInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Lemonade.Net.Protocol.GachaInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GachaInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GachaInfo(GachaInfo other) : this() {
      gachaType_ = other.gachaType_;
      scheduleId_ = other.scheduleId_;
      beginTime_ = other.beginTime_;
      endTime_ = other.endTime_;
      costItemId_ = other.costItemId_;
      costItemNum_ = other.costItemNum_;
      gachaPrefabPath_ = other.gachaPrefabPath_;
      gachaProbUrl_ = other.gachaProbUrl_;
      gachaRecordUrl_ = other.gachaRecordUrl_;
      gachaPreviewPrefabPath_ = other.gachaPreviewPrefabPath_;
      tenCostItemId_ = other.tenCostItemId_;
      tenCostItemNum_ = other.tenCostItemNum_;
      leftGachaTimes_ = other.leftGachaTimes_;
      gachaTimesLimit_ = other.gachaTimesLimit_;
      gachaSortId_ = other.gachaSortId_;
      gachaProbUrlOversea_ = other.gachaProbUrlOversea_;
      gachaRecordUrlOversea_ = other.gachaRecordUrlOversea_;
      gachaUpInfoList_ = other.gachaUpInfoList_.Clone();
      gachaTitlePath_ = other.gachaTitlePath_;
      mainNameId_ = other.mainNameId_.Clone();
      subNameId_ = other.subNameId_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GachaInfo Clone() {
      return new GachaInfo(this);
    }

    /// <summary>Field number for the "gachaType" field.</summary>
    public const int GachaTypeFieldNumber = 1;
    private uint gachaType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint GachaType {
      get { return gachaType_; }
      set {
        gachaType_ = value;
      }
    }

    /// <summary>Field number for the "scheduleId" field.</summary>
    public const int ScheduleIdFieldNumber = 2;
    private uint scheduleId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ScheduleId {
      get { return scheduleId_; }
      set {
        scheduleId_ = value;
      }
    }

    /// <summary>Field number for the "beginTime" field.</summary>
    public const int BeginTimeFieldNumber = 3;
    private uint beginTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint BeginTime {
      get { return beginTime_; }
      set {
        beginTime_ = value;
      }
    }

    /// <summary>Field number for the "endTime" field.</summary>
    public const int EndTimeFieldNumber = 4;
    private uint endTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint EndTime {
      get { return endTime_; }
      set {
        endTime_ = value;
      }
    }

    /// <summary>Field number for the "costItemId" field.</summary>
    public const int CostItemIdFieldNumber = 5;
    private uint costItemId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CostItemId {
      get { return costItemId_; }
      set {
        costItemId_ = value;
      }
    }

    /// <summary>Field number for the "costItemNum" field.</summary>
    public const int CostItemNumFieldNumber = 6;
    private uint costItemNum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CostItemNum {
      get { return costItemNum_; }
      set {
        costItemNum_ = value;
      }
    }

    /// <summary>Field number for the "gachaPrefabPath" field.</summary>
    public const int GachaPrefabPathFieldNumber = 7;
    private string gachaPrefabPath_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GachaPrefabPath {
      get { return gachaPrefabPath_; }
      set {
        gachaPrefabPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gachaProbUrl" field.</summary>
    public const int GachaProbUrlFieldNumber = 8;
    private string gachaProbUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GachaProbUrl {
      get { return gachaProbUrl_; }
      set {
        gachaProbUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gachaRecordUrl" field.</summary>
    public const int GachaRecordUrlFieldNumber = 9;
    private string gachaRecordUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GachaRecordUrl {
      get { return gachaRecordUrl_; }
      set {
        gachaRecordUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gachaPreviewPrefabPath" field.</summary>
    public const int GachaPreviewPrefabPathFieldNumber = 10;
    private string gachaPreviewPrefabPath_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GachaPreviewPrefabPath {
      get { return gachaPreviewPrefabPath_; }
      set {
        gachaPreviewPrefabPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tenCostItemId" field.</summary>
    public const int TenCostItemIdFieldNumber = 11;
    private uint tenCostItemId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TenCostItemId {
      get { return tenCostItemId_; }
      set {
        tenCostItemId_ = value;
      }
    }

    /// <summary>Field number for the "tenCostItemNum" field.</summary>
    public const int TenCostItemNumFieldNumber = 12;
    private uint tenCostItemNum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TenCostItemNum {
      get { return tenCostItemNum_; }
      set {
        tenCostItemNum_ = value;
      }
    }

    /// <summary>Field number for the "leftGachaTimes" field.</summary>
    public const int LeftGachaTimesFieldNumber = 13;
    private uint leftGachaTimes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint LeftGachaTimes {
      get { return leftGachaTimes_; }
      set {
        leftGachaTimes_ = value;
      }
    }

    /// <summary>Field number for the "gachaTimesLimit" field.</summary>
    public const int GachaTimesLimitFieldNumber = 14;
    private uint gachaTimesLimit_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint GachaTimesLimit {
      get { return gachaTimesLimit_; }
      set {
        gachaTimesLimit_ = value;
      }
    }

    /// <summary>Field number for the "gachaSortId" field.</summary>
    public const int GachaSortIdFieldNumber = 15;
    private uint gachaSortId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint GachaSortId {
      get { return gachaSortId_; }
      set {
        gachaSortId_ = value;
      }
    }

    /// <summary>Field number for the "gachaProbUrlOversea" field.</summary>
    public const int GachaProbUrlOverseaFieldNumber = 16;
    private string gachaProbUrlOversea_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GachaProbUrlOversea {
      get { return gachaProbUrlOversea_; }
      set {
        gachaProbUrlOversea_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gachaRecordUrlOversea" field.</summary>
    public const int GachaRecordUrlOverseaFieldNumber = 17;
    private string gachaRecordUrlOversea_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GachaRecordUrlOversea {
      get { return gachaRecordUrlOversea_; }
      set {
        gachaRecordUrlOversea_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gachaUpInfoList" field.</summary>
    public const int GachaUpInfoListFieldNumber = 18;
    private static readonly pb::FieldCodec<global::Lemonade.Net.Protocol.GachaUpInfo> _repeated_gachaUpInfoList_codec
        = pb::FieldCodec.ForMessage(146, global::Lemonade.Net.Protocol.GachaUpInfo.Parser);
    private readonly pbc::RepeatedField<global::Lemonade.Net.Protocol.GachaUpInfo> gachaUpInfoList_ = new pbc::RepeatedField<global::Lemonade.Net.Protocol.GachaUpInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Lemonade.Net.Protocol.GachaUpInfo> GachaUpInfoList {
      get { return gachaUpInfoList_; }
    }

    /// <summary>Field number for the "gachaTitlePath" field.</summary>
    public const int GachaTitlePathFieldNumber = 19;
    private string gachaTitlePath_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GachaTitlePath {
      get { return gachaTitlePath_; }
      set {
        gachaTitlePath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mainNameId" field.</summary>
    public const int MainNameIdFieldNumber = 20;
    private static readonly pb::FieldCodec<uint> _repeated_mainNameId_codec
        = pb::FieldCodec.ForUInt32(162);
    private readonly pbc::RepeatedField<uint> mainNameId_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> MainNameId {
      get { return mainNameId_; }
    }

    /// <summary>Field number for the "subNameId" field.</summary>
    public const int SubNameIdFieldNumber = 21;
    private static readonly pb::FieldCodec<uint> _repeated_subNameId_codec
        = pb::FieldCodec.ForUInt32(170);
    private readonly pbc::RepeatedField<uint> subNameId_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> SubNameId {
      get { return subNameId_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GachaInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GachaInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GachaType != other.GachaType) return false;
      if (ScheduleId != other.ScheduleId) return false;
      if (BeginTime != other.BeginTime) return false;
      if (EndTime != other.EndTime) return false;
      if (CostItemId != other.CostItemId) return false;
      if (CostItemNum != other.CostItemNum) return false;
      if (GachaPrefabPath != other.GachaPrefabPath) return false;
      if (GachaProbUrl != other.GachaProbUrl) return false;
      if (GachaRecordUrl != other.GachaRecordUrl) return false;
      if (GachaPreviewPrefabPath != other.GachaPreviewPrefabPath) return false;
      if (TenCostItemId != other.TenCostItemId) return false;
      if (TenCostItemNum != other.TenCostItemNum) return false;
      if (LeftGachaTimes != other.LeftGachaTimes) return false;
      if (GachaTimesLimit != other.GachaTimesLimit) return false;
      if (GachaSortId != other.GachaSortId) return false;
      if (GachaProbUrlOversea != other.GachaProbUrlOversea) return false;
      if (GachaRecordUrlOversea != other.GachaRecordUrlOversea) return false;
      if(!gachaUpInfoList_.Equals(other.gachaUpInfoList_)) return false;
      if (GachaTitlePath != other.GachaTitlePath) return false;
      if(!mainNameId_.Equals(other.mainNameId_)) return false;
      if(!subNameId_.Equals(other.subNameId_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (GachaType != 0) hash ^= GachaType.GetHashCode();
      if (ScheduleId != 0) hash ^= ScheduleId.GetHashCode();
      if (BeginTime != 0) hash ^= BeginTime.GetHashCode();
      if (EndTime != 0) hash ^= EndTime.GetHashCode();
      if (CostItemId != 0) hash ^= CostItemId.GetHashCode();
      if (CostItemNum != 0) hash ^= CostItemNum.GetHashCode();
      if (GachaPrefabPath.Length != 0) hash ^= GachaPrefabPath.GetHashCode();
      if (GachaProbUrl.Length != 0) hash ^= GachaProbUrl.GetHashCode();
      if (GachaRecordUrl.Length != 0) hash ^= GachaRecordUrl.GetHashCode();
      if (GachaPreviewPrefabPath.Length != 0) hash ^= GachaPreviewPrefabPath.GetHashCode();
      if (TenCostItemId != 0) hash ^= TenCostItemId.GetHashCode();
      if (TenCostItemNum != 0) hash ^= TenCostItemNum.GetHashCode();
      if (LeftGachaTimes != 0) hash ^= LeftGachaTimes.GetHashCode();
      if (GachaTimesLimit != 0) hash ^= GachaTimesLimit.GetHashCode();
      if (GachaSortId != 0) hash ^= GachaSortId.GetHashCode();
      if (GachaProbUrlOversea.Length != 0) hash ^= GachaProbUrlOversea.GetHashCode();
      if (GachaRecordUrlOversea.Length != 0) hash ^= GachaRecordUrlOversea.GetHashCode();
      hash ^= gachaUpInfoList_.GetHashCode();
      if (GachaTitlePath.Length != 0) hash ^= GachaTitlePath.GetHashCode();
      hash ^= mainNameId_.GetHashCode();
      hash ^= subNameId_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (GachaType != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(GachaType);
      }
      if (ScheduleId != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(ScheduleId);
      }
      if (BeginTime != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(BeginTime);
      }
      if (EndTime != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(EndTime);
      }
      if (CostItemId != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(CostItemId);
      }
      if (CostItemNum != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(CostItemNum);
      }
      if (GachaPrefabPath.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(GachaPrefabPath);
      }
      if (GachaProbUrl.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(GachaProbUrl);
      }
      if (GachaRecordUrl.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(GachaRecordUrl);
      }
      if (GachaPreviewPrefabPath.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(GachaPreviewPrefabPath);
      }
      if (TenCostItemId != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(TenCostItemId);
      }
      if (TenCostItemNum != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(TenCostItemNum);
      }
      if (LeftGachaTimes != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(LeftGachaTimes);
      }
      if (GachaTimesLimit != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(GachaTimesLimit);
      }
      if (GachaSortId != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(GachaSortId);
      }
      if (GachaProbUrlOversea.Length != 0) {
        output.WriteRawTag(130, 1);
        output.WriteString(GachaProbUrlOversea);
      }
      if (GachaRecordUrlOversea.Length != 0) {
        output.WriteRawTag(138, 1);
        output.WriteString(GachaRecordUrlOversea);
      }
      gachaUpInfoList_.WriteTo(output, _repeated_gachaUpInfoList_codec);
      if (GachaTitlePath.Length != 0) {
        output.WriteRawTag(154, 1);
        output.WriteString(GachaTitlePath);
      }
      mainNameId_.WriteTo(output, _repeated_mainNameId_codec);
      subNameId_.WriteTo(output, _repeated_subNameId_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (GachaType != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(GachaType);
      }
      if (ScheduleId != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(ScheduleId);
      }
      if (BeginTime != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(BeginTime);
      }
      if (EndTime != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(EndTime);
      }
      if (CostItemId != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(CostItemId);
      }
      if (CostItemNum != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(CostItemNum);
      }
      if (GachaPrefabPath.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(GachaPrefabPath);
      }
      if (GachaProbUrl.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(GachaProbUrl);
      }
      if (GachaRecordUrl.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(GachaRecordUrl);
      }
      if (GachaPreviewPrefabPath.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(GachaPreviewPrefabPath);
      }
      if (TenCostItemId != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(TenCostItemId);
      }
      if (TenCostItemNum != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(TenCostItemNum);
      }
      if (LeftGachaTimes != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(LeftGachaTimes);
      }
      if (GachaTimesLimit != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(GachaTimesLimit);
      }
      if (GachaSortId != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(GachaSortId);
      }
      if (GachaProbUrlOversea.Length != 0) {
        output.WriteRawTag(130, 1);
        output.WriteString(GachaProbUrlOversea);
      }
      if (GachaRecordUrlOversea.Length != 0) {
        output.WriteRawTag(138, 1);
        output.WriteString(GachaRecordUrlOversea);
      }
      gachaUpInfoList_.WriteTo(ref output, _repeated_gachaUpInfoList_codec);
      if (GachaTitlePath.Length != 0) {
        output.WriteRawTag(154, 1);
        output.WriteString(GachaTitlePath);
      }
      mainNameId_.WriteTo(ref output, _repeated_mainNameId_codec);
      subNameId_.WriteTo(ref output, _repeated_subNameId_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (GachaType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GachaType);
      }
      if (ScheduleId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ScheduleId);
      }
      if (BeginTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BeginTime);
      }
      if (EndTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EndTime);
      }
      if (CostItemId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CostItemId);
      }
      if (CostItemNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CostItemNum);
      }
      if (GachaPrefabPath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GachaPrefabPath);
      }
      if (GachaProbUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GachaProbUrl);
      }
      if (GachaRecordUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GachaRecordUrl);
      }
      if (GachaPreviewPrefabPath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GachaPreviewPrefabPath);
      }
      if (TenCostItemId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TenCostItemId);
      }
      if (TenCostItemNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TenCostItemNum);
      }
      if (LeftGachaTimes != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LeftGachaTimes);
      }
      if (GachaTimesLimit != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GachaTimesLimit);
      }
      if (GachaSortId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GachaSortId);
      }
      if (GachaProbUrlOversea.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(GachaProbUrlOversea);
      }
      if (GachaRecordUrlOversea.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(GachaRecordUrlOversea);
      }
      size += gachaUpInfoList_.CalculateSize(_repeated_gachaUpInfoList_codec);
      if (GachaTitlePath.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(GachaTitlePath);
      }
      size += mainNameId_.CalculateSize(_repeated_mainNameId_codec);
      size += subNameId_.CalculateSize(_repeated_subNameId_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GachaInfo other) {
      if (other == null) {
        return;
      }
      if (other.GachaType != 0) {
        GachaType = other.GachaType;
      }
      if (other.ScheduleId != 0) {
        ScheduleId = other.ScheduleId;
      }
      if (other.BeginTime != 0) {
        BeginTime = other.BeginTime;
      }
      if (other.EndTime != 0) {
        EndTime = other.EndTime;
      }
      if (other.CostItemId != 0) {
        CostItemId = other.CostItemId;
      }
      if (other.CostItemNum != 0) {
        CostItemNum = other.CostItemNum;
      }
      if (other.GachaPrefabPath.Length != 0) {
        GachaPrefabPath = other.GachaPrefabPath;
      }
      if (other.GachaProbUrl.Length != 0) {
        GachaProbUrl = other.GachaProbUrl;
      }
      if (other.GachaRecordUrl.Length != 0) {
        GachaRecordUrl = other.GachaRecordUrl;
      }
      if (other.GachaPreviewPrefabPath.Length != 0) {
        GachaPreviewPrefabPath = other.GachaPreviewPrefabPath;
      }
      if (other.TenCostItemId != 0) {
        TenCostItemId = other.TenCostItemId;
      }
      if (other.TenCostItemNum != 0) {
        TenCostItemNum = other.TenCostItemNum;
      }
      if (other.LeftGachaTimes != 0) {
        LeftGachaTimes = other.LeftGachaTimes;
      }
      if (other.GachaTimesLimit != 0) {
        GachaTimesLimit = other.GachaTimesLimit;
      }
      if (other.GachaSortId != 0) {
        GachaSortId = other.GachaSortId;
      }
      if (other.GachaProbUrlOversea.Length != 0) {
        GachaProbUrlOversea = other.GachaProbUrlOversea;
      }
      if (other.GachaRecordUrlOversea.Length != 0) {
        GachaRecordUrlOversea = other.GachaRecordUrlOversea;
      }
      gachaUpInfoList_.Add(other.gachaUpInfoList_);
      if (other.GachaTitlePath.Length != 0) {
        GachaTitlePath = other.GachaTitlePath;
      }
      mainNameId_.Add(other.mainNameId_);
      subNameId_.Add(other.subNameId_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            GachaType = input.ReadUInt32();
            break;
          }
          case 16: {
            ScheduleId = input.ReadUInt32();
            break;
          }
          case 24: {
            BeginTime = input.ReadUInt32();
            break;
          }
          case 32: {
            EndTime = input.ReadUInt32();
            break;
          }
          case 40: {
            CostItemId = input.ReadUInt32();
            break;
          }
          case 48: {
            CostItemNum = input.ReadUInt32();
            break;
          }
          case 58: {
            GachaPrefabPath = input.ReadString();
            break;
          }
          case 66: {
            GachaProbUrl = input.ReadString();
            break;
          }
          case 74: {
            GachaRecordUrl = input.ReadString();
            break;
          }
          case 82: {
            GachaPreviewPrefabPath = input.ReadString();
            break;
          }
          case 88: {
            TenCostItemId = input.ReadUInt32();
            break;
          }
          case 96: {
            TenCostItemNum = input.ReadUInt32();
            break;
          }
          case 104: {
            LeftGachaTimes = input.ReadUInt32();
            break;
          }
          case 112: {
            GachaTimesLimit = input.ReadUInt32();
            break;
          }
          case 120: {
            GachaSortId = input.ReadUInt32();
            break;
          }
          case 130: {
            GachaProbUrlOversea = input.ReadString();
            break;
          }
          case 138: {
            GachaRecordUrlOversea = input.ReadString();
            break;
          }
          case 146: {
            gachaUpInfoList_.AddEntriesFrom(input, _repeated_gachaUpInfoList_codec);
            break;
          }
          case 154: {
            GachaTitlePath = input.ReadString();
            break;
          }
          case 162:
          case 160: {
            mainNameId_.AddEntriesFrom(input, _repeated_mainNameId_codec);
            break;
          }
          case 170:
          case 168: {
            subNameId_.AddEntriesFrom(input, _repeated_subNameId_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            GachaType = input.ReadUInt32();
            break;
          }
          case 16: {
            ScheduleId = input.ReadUInt32();
            break;
          }
          case 24: {
            BeginTime = input.ReadUInt32();
            break;
          }
          case 32: {
            EndTime = input.ReadUInt32();
            break;
          }
          case 40: {
            CostItemId = input.ReadUInt32();
            break;
          }
          case 48: {
            CostItemNum = input.ReadUInt32();
            break;
          }
          case 58: {
            GachaPrefabPath = input.ReadString();
            break;
          }
          case 66: {
            GachaProbUrl = input.ReadString();
            break;
          }
          case 74: {
            GachaRecordUrl = input.ReadString();
            break;
          }
          case 82: {
            GachaPreviewPrefabPath = input.ReadString();
            break;
          }
          case 88: {
            TenCostItemId = input.ReadUInt32();
            break;
          }
          case 96: {
            TenCostItemNum = input.ReadUInt32();
            break;
          }
          case 104: {
            LeftGachaTimes = input.ReadUInt32();
            break;
          }
          case 112: {
            GachaTimesLimit = input.ReadUInt32();
            break;
          }
          case 120: {
            GachaSortId = input.ReadUInt32();
            break;
          }
          case 130: {
            GachaProbUrlOversea = input.ReadString();
            break;
          }
          case 138: {
            GachaRecordUrlOversea = input.ReadString();
            break;
          }
          case 146: {
            gachaUpInfoList_.AddEntriesFrom(ref input, _repeated_gachaUpInfoList_codec);
            break;
          }
          case 154: {
            GachaTitlePath = input.ReadString();
            break;
          }
          case 162:
          case 160: {
            mainNameId_.AddEntriesFrom(ref input, _repeated_mainNameId_codec);
            break;
          }
          case 170:
          case 168: {
            subNameId_.AddEntriesFrom(ref input, _repeated_subNameId_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
