// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GadgetBornType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Lemonade.Net.Protocol {

  /// <summary>Holder for reflection information generated from GadgetBornType.proto</summary>
  public static partial class GadgetBornTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for GadgetBornType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GadgetBornTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRHYWRnZXRCb3JuVHlwZS5wcm90byrAAQoOR2FkZ2V0Qm9yblR5cGUSFAoQ",
            "R0FER0VUX0JPUk5fTk9ORRAAEhYKEkdBREdFVF9CT1JOX0lOX0FJUhABEhYK",
            "EkdBREdFVF9CT1JOX1BMQVlFUhACEhsKF0dBREdFVF9CT1JOX01PTlNURVJf",
            "SElUEAMSGwoXR0FER0VUX0JPUk5fTU9OU1RFUl9ESUUQBBIWChJHQURHRVRf",
            "Qk9STl9HQURHRVQQBRIWChJHQURHRVRfQk9STl9HUk9VTkQQBkIYqgIVTGVt",
            "b25hZGUuTmV0LlByb3RvY29sYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Lemonade.Net.Protocol.GadgetBornType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum GadgetBornType {
    [pbr::OriginalName("GADGET_BORN_NONE")] GadgetBornNone = 0,
    [pbr::OriginalName("GADGET_BORN_IN_AIR")] GadgetBornInAir = 1,
    [pbr::OriginalName("GADGET_BORN_PLAYER")] GadgetBornPlayer = 2,
    [pbr::OriginalName("GADGET_BORN_MONSTER_HIT")] GadgetBornMonsterHit = 3,
    [pbr::OriginalName("GADGET_BORN_MONSTER_DIE")] GadgetBornMonsterDie = 4,
    [pbr::OriginalName("GADGET_BORN_GADGET")] GadgetBornGadget = 5,
    [pbr::OriginalName("GADGET_BORN_GROUND")] GadgetBornGround = 6,
  }

  #endregion

}

#endregion Designer generated code
