// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GetScenePointRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Lemonade.Net.Protocol {

  /// <summary>Holder for reflection information generated from GetScenePointRsp.proto</summary>
  public static partial class GetScenePointRspReflection {

    #region Descriptor
    /// <summary>File descriptor for GetScenePointRsp.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GetScenePointRspReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZHZXRTY2VuZVBvaW50UnNwLnByb3RvIqEDChBHZXRTY2VuZVBvaW50UnNw",
            "Eg8KB3JldGNvZGUYASABKAUSEAoIc2NlbmVfaWQYAiABKA0SGwoTdW5sb2Nr",
            "ZWRfcG9pbnRfbGlzdBgDIAMoDRISCgpiZWxvbmdfdWlkGAQgASgNEhgKEHVu",
            "bG9ja19hcmVhX2xpc3QYBSADKA0SGQoRbG9ja2VkX3BvaW50X2xpc3QYBiAD",
            "KA0SKAogdG9fYmVfZXhwbG9yZV9kdW5nZW9uX2VudHJ5X2xpc3QYByADKA0S",
            "Jwofbm90X2V4cGxvcmVkX2R1bmdlb25fZW50cnlfbGlzdBgIIAMoDRIgChhn",
            "cm91cF91bmxpbWl0X3BvaW50X2xpc3QYCSADKA0SJwofbm90X2ludGVyYWN0",
            "X2R1bmdlb25fZW50cnlfbGlzdBgKIAMoDRIXCg9oaWRlX3BvaW50X2xpc3QY",
            "CyADKA0iTQoFQ21kSWQSCAoETk9ORRAAEhMKD0VORVRfQ0hBTk5FTF9JRBAA",
            "EhQKEEVORVRfSVNfUkVMSUFCTEUQARILCgZDTURfSUQQ7AEaAhABQhiqAhVM",
            "ZW1vbmFkZS5OZXQuUHJvdG9jb2xiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Lemonade.Net.Protocol.GetScenePointRsp), global::Lemonade.Net.Protocol.GetScenePointRsp.Parser, new[]{ "Retcode", "SceneId", "UnlockedPointList", "BelongUid", "UnlockAreaList", "LockedPointList", "ToBeExploreDungeonEntryList", "NotExploredDungeonEntryList", "GroupUnlimitPointList", "NotInteractDungeonEntryList", "HidePointList" }, null, new[]{ typeof(global::Lemonade.Net.Protocol.GetScenePointRsp.Types.CmdId) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GetScenePointRsp : pb::IMessage<GetScenePointRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetScenePointRsp> _parser = new pb::MessageParser<GetScenePointRsp>(() => new GetScenePointRsp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetScenePointRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Lemonade.Net.Protocol.GetScenePointRspReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetScenePointRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetScenePointRsp(GetScenePointRsp other) : this() {
      retcode_ = other.retcode_;
      sceneId_ = other.sceneId_;
      unlockedPointList_ = other.unlockedPointList_.Clone();
      belongUid_ = other.belongUid_;
      unlockAreaList_ = other.unlockAreaList_.Clone();
      lockedPointList_ = other.lockedPointList_.Clone();
      toBeExploreDungeonEntryList_ = other.toBeExploreDungeonEntryList_.Clone();
      notExploredDungeonEntryList_ = other.notExploredDungeonEntryList_.Clone();
      groupUnlimitPointList_ = other.groupUnlimitPointList_.Clone();
      notInteractDungeonEntryList_ = other.notInteractDungeonEntryList_.Clone();
      hidePointList_ = other.hidePointList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetScenePointRsp Clone() {
      return new GetScenePointRsp(this);
    }

    /// <summary>Field number for the "retcode" field.</summary>
    public const int RetcodeFieldNumber = 1;
    private int retcode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Retcode {
      get { return retcode_; }
      set {
        retcode_ = value;
      }
    }

    /// <summary>Field number for the "scene_id" field.</summary>
    public const int SceneIdFieldNumber = 2;
    private uint sceneId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint SceneId {
      get { return sceneId_; }
      set {
        sceneId_ = value;
      }
    }

    /// <summary>Field number for the "unlocked_point_list" field.</summary>
    public const int UnlockedPointListFieldNumber = 3;
    private static readonly pb::FieldCodec<uint> _repeated_unlockedPointList_codec
        = pb::FieldCodec.ForUInt32(26);
    private readonly pbc::RepeatedField<uint> unlockedPointList_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> UnlockedPointList {
      get { return unlockedPointList_; }
    }

    /// <summary>Field number for the "belong_uid" field.</summary>
    public const int BelongUidFieldNumber = 4;
    private uint belongUid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint BelongUid {
      get { return belongUid_; }
      set {
        belongUid_ = value;
      }
    }

    /// <summary>Field number for the "unlock_area_list" field.</summary>
    public const int UnlockAreaListFieldNumber = 5;
    private static readonly pb::FieldCodec<uint> _repeated_unlockAreaList_codec
        = pb::FieldCodec.ForUInt32(42);
    private readonly pbc::RepeatedField<uint> unlockAreaList_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> UnlockAreaList {
      get { return unlockAreaList_; }
    }

    /// <summary>Field number for the "locked_point_list" field.</summary>
    public const int LockedPointListFieldNumber = 6;
    private static readonly pb::FieldCodec<uint> _repeated_lockedPointList_codec
        = pb::FieldCodec.ForUInt32(50);
    private readonly pbc::RepeatedField<uint> lockedPointList_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> LockedPointList {
      get { return lockedPointList_; }
    }

    /// <summary>Field number for the "to_be_explore_dungeon_entry_list" field.</summary>
    public const int ToBeExploreDungeonEntryListFieldNumber = 7;
    private static readonly pb::FieldCodec<uint> _repeated_toBeExploreDungeonEntryList_codec
        = pb::FieldCodec.ForUInt32(58);
    private readonly pbc::RepeatedField<uint> toBeExploreDungeonEntryList_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> ToBeExploreDungeonEntryList {
      get { return toBeExploreDungeonEntryList_; }
    }

    /// <summary>Field number for the "not_explored_dungeon_entry_list" field.</summary>
    public const int NotExploredDungeonEntryListFieldNumber = 8;
    private static readonly pb::FieldCodec<uint> _repeated_notExploredDungeonEntryList_codec
        = pb::FieldCodec.ForUInt32(66);
    private readonly pbc::RepeatedField<uint> notExploredDungeonEntryList_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> NotExploredDungeonEntryList {
      get { return notExploredDungeonEntryList_; }
    }

    /// <summary>Field number for the "group_unlimit_point_list" field.</summary>
    public const int GroupUnlimitPointListFieldNumber = 9;
    private static readonly pb::FieldCodec<uint> _repeated_groupUnlimitPointList_codec
        = pb::FieldCodec.ForUInt32(74);
    private readonly pbc::RepeatedField<uint> groupUnlimitPointList_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> GroupUnlimitPointList {
      get { return groupUnlimitPointList_; }
    }

    /// <summary>Field number for the "not_interact_dungeon_entry_list" field.</summary>
    public const int NotInteractDungeonEntryListFieldNumber = 10;
    private static readonly pb::FieldCodec<uint> _repeated_notInteractDungeonEntryList_codec
        = pb::FieldCodec.ForUInt32(82);
    private readonly pbc::RepeatedField<uint> notInteractDungeonEntryList_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> NotInteractDungeonEntryList {
      get { return notInteractDungeonEntryList_; }
    }

    /// <summary>Field number for the "hide_point_list" field.</summary>
    public const int HidePointListFieldNumber = 11;
    private static readonly pb::FieldCodec<uint> _repeated_hidePointList_codec
        = pb::FieldCodec.ForUInt32(90);
    private readonly pbc::RepeatedField<uint> hidePointList_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> HidePointList {
      get { return hidePointList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetScenePointRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetScenePointRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Retcode != other.Retcode) return false;
      if (SceneId != other.SceneId) return false;
      if(!unlockedPointList_.Equals(other.unlockedPointList_)) return false;
      if (BelongUid != other.BelongUid) return false;
      if(!unlockAreaList_.Equals(other.unlockAreaList_)) return false;
      if(!lockedPointList_.Equals(other.lockedPointList_)) return false;
      if(!toBeExploreDungeonEntryList_.Equals(other.toBeExploreDungeonEntryList_)) return false;
      if(!notExploredDungeonEntryList_.Equals(other.notExploredDungeonEntryList_)) return false;
      if(!groupUnlimitPointList_.Equals(other.groupUnlimitPointList_)) return false;
      if(!notInteractDungeonEntryList_.Equals(other.notInteractDungeonEntryList_)) return false;
      if(!hidePointList_.Equals(other.hidePointList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Retcode != 0) hash ^= Retcode.GetHashCode();
      if (SceneId != 0) hash ^= SceneId.GetHashCode();
      hash ^= unlockedPointList_.GetHashCode();
      if (BelongUid != 0) hash ^= BelongUid.GetHashCode();
      hash ^= unlockAreaList_.GetHashCode();
      hash ^= lockedPointList_.GetHashCode();
      hash ^= toBeExploreDungeonEntryList_.GetHashCode();
      hash ^= notExploredDungeonEntryList_.GetHashCode();
      hash ^= groupUnlimitPointList_.GetHashCode();
      hash ^= notInteractDungeonEntryList_.GetHashCode();
      hash ^= hidePointList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Retcode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Retcode);
      }
      if (SceneId != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(SceneId);
      }
      unlockedPointList_.WriteTo(output, _repeated_unlockedPointList_codec);
      if (BelongUid != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(BelongUid);
      }
      unlockAreaList_.WriteTo(output, _repeated_unlockAreaList_codec);
      lockedPointList_.WriteTo(output, _repeated_lockedPointList_codec);
      toBeExploreDungeonEntryList_.WriteTo(output, _repeated_toBeExploreDungeonEntryList_codec);
      notExploredDungeonEntryList_.WriteTo(output, _repeated_notExploredDungeonEntryList_codec);
      groupUnlimitPointList_.WriteTo(output, _repeated_groupUnlimitPointList_codec);
      notInteractDungeonEntryList_.WriteTo(output, _repeated_notInteractDungeonEntryList_codec);
      hidePointList_.WriteTo(output, _repeated_hidePointList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Retcode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Retcode);
      }
      if (SceneId != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(SceneId);
      }
      unlockedPointList_.WriteTo(ref output, _repeated_unlockedPointList_codec);
      if (BelongUid != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(BelongUid);
      }
      unlockAreaList_.WriteTo(ref output, _repeated_unlockAreaList_codec);
      lockedPointList_.WriteTo(ref output, _repeated_lockedPointList_codec);
      toBeExploreDungeonEntryList_.WriteTo(ref output, _repeated_toBeExploreDungeonEntryList_codec);
      notExploredDungeonEntryList_.WriteTo(ref output, _repeated_notExploredDungeonEntryList_codec);
      groupUnlimitPointList_.WriteTo(ref output, _repeated_groupUnlimitPointList_codec);
      notInteractDungeonEntryList_.WriteTo(ref output, _repeated_notInteractDungeonEntryList_codec);
      hidePointList_.WriteTo(ref output, _repeated_hidePointList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Retcode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Retcode);
      }
      if (SceneId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SceneId);
      }
      size += unlockedPointList_.CalculateSize(_repeated_unlockedPointList_codec);
      if (BelongUid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BelongUid);
      }
      size += unlockAreaList_.CalculateSize(_repeated_unlockAreaList_codec);
      size += lockedPointList_.CalculateSize(_repeated_lockedPointList_codec);
      size += toBeExploreDungeonEntryList_.CalculateSize(_repeated_toBeExploreDungeonEntryList_codec);
      size += notExploredDungeonEntryList_.CalculateSize(_repeated_notExploredDungeonEntryList_codec);
      size += groupUnlimitPointList_.CalculateSize(_repeated_groupUnlimitPointList_codec);
      size += notInteractDungeonEntryList_.CalculateSize(_repeated_notInteractDungeonEntryList_codec);
      size += hidePointList_.CalculateSize(_repeated_hidePointList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetScenePointRsp other) {
      if (other == null) {
        return;
      }
      if (other.Retcode != 0) {
        Retcode = other.Retcode;
      }
      if (other.SceneId != 0) {
        SceneId = other.SceneId;
      }
      unlockedPointList_.Add(other.unlockedPointList_);
      if (other.BelongUid != 0) {
        BelongUid = other.BelongUid;
      }
      unlockAreaList_.Add(other.unlockAreaList_);
      lockedPointList_.Add(other.lockedPointList_);
      toBeExploreDungeonEntryList_.Add(other.toBeExploreDungeonEntryList_);
      notExploredDungeonEntryList_.Add(other.notExploredDungeonEntryList_);
      groupUnlimitPointList_.Add(other.groupUnlimitPointList_);
      notInteractDungeonEntryList_.Add(other.notInteractDungeonEntryList_);
      hidePointList_.Add(other.hidePointList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Retcode = input.ReadInt32();
            break;
          }
          case 16: {
            SceneId = input.ReadUInt32();
            break;
          }
          case 26:
          case 24: {
            unlockedPointList_.AddEntriesFrom(input, _repeated_unlockedPointList_codec);
            break;
          }
          case 32: {
            BelongUid = input.ReadUInt32();
            break;
          }
          case 42:
          case 40: {
            unlockAreaList_.AddEntriesFrom(input, _repeated_unlockAreaList_codec);
            break;
          }
          case 50:
          case 48: {
            lockedPointList_.AddEntriesFrom(input, _repeated_lockedPointList_codec);
            break;
          }
          case 58:
          case 56: {
            toBeExploreDungeonEntryList_.AddEntriesFrom(input, _repeated_toBeExploreDungeonEntryList_codec);
            break;
          }
          case 66:
          case 64: {
            notExploredDungeonEntryList_.AddEntriesFrom(input, _repeated_notExploredDungeonEntryList_codec);
            break;
          }
          case 74:
          case 72: {
            groupUnlimitPointList_.AddEntriesFrom(input, _repeated_groupUnlimitPointList_codec);
            break;
          }
          case 82:
          case 80: {
            notInteractDungeonEntryList_.AddEntriesFrom(input, _repeated_notInteractDungeonEntryList_codec);
            break;
          }
          case 90:
          case 88: {
            hidePointList_.AddEntriesFrom(input, _repeated_hidePointList_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Retcode = input.ReadInt32();
            break;
          }
          case 16: {
            SceneId = input.ReadUInt32();
            break;
          }
          case 26:
          case 24: {
            unlockedPointList_.AddEntriesFrom(ref input, _repeated_unlockedPointList_codec);
            break;
          }
          case 32: {
            BelongUid = input.ReadUInt32();
            break;
          }
          case 42:
          case 40: {
            unlockAreaList_.AddEntriesFrom(ref input, _repeated_unlockAreaList_codec);
            break;
          }
          case 50:
          case 48: {
            lockedPointList_.AddEntriesFrom(ref input, _repeated_lockedPointList_codec);
            break;
          }
          case 58:
          case 56: {
            toBeExploreDungeonEntryList_.AddEntriesFrom(ref input, _repeated_toBeExploreDungeonEntryList_codec);
            break;
          }
          case 66:
          case 64: {
            notExploredDungeonEntryList_.AddEntriesFrom(ref input, _repeated_notExploredDungeonEntryList_codec);
            break;
          }
          case 74:
          case 72: {
            groupUnlimitPointList_.AddEntriesFrom(ref input, _repeated_groupUnlimitPointList_codec);
            break;
          }
          case 82:
          case 80: {
            notInteractDungeonEntryList_.AddEntriesFrom(ref input, _repeated_notInteractDungeonEntryList_codec);
            break;
          }
          case 90:
          case 88: {
            hidePointList_.AddEntriesFrom(ref input, _repeated_hidePointList_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the GetScenePointRsp message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum CmdId {
        [pbr::OriginalName("NONE")] None = 0,
        [pbr::OriginalName("ENET_CHANNEL_ID", PreferredAlias = false)] EnetChannelId = 0,
        [pbr::OriginalName("ENET_IS_RELIABLE")] EnetIsReliable = 1,
        [pbr::OriginalName("CMD_ID")] CmdId = 236,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
