// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MapMarkTipsType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Lemonade.Net.Protocol {

  /// <summary>Holder for reflection information generated from MapMarkTipsType.proto</summary>
  public static partial class MapMarkTipsTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for MapMarkTipsType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MapMarkTipsTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVNYXBNYXJrVGlwc1R5cGUucHJvdG8qNgoPTWFwTWFya1RpcHNUeXBlEiMK",
            "H01BUktfVElQU19EVU5HRU9OX0VMRU1FTlRfVFJJQUwQAEIYqgIVTGVtb25h",
            "ZGUuTmV0LlByb3RvY29sYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Lemonade.Net.Protocol.MapMarkTipsType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MapMarkTipsType {
    [pbr::OriginalName("MARK_TIPS_DUNGEON_ELEMENT_TRIAL")] MarkTipsDungeonElementTrial = 0,
  }

  #endregion

}

#endregion Designer generated code
