// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Operation.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Lemonade.Net.Protocol {

  /// <summary>Holder for reflection information generated from Operation.proto</summary>
  public static partial class OperationReflection {

    #region Descriptor
    /// <summary>File descriptor for Operation.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OperationReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9PcGVyYXRpb24ucHJvdG8qLwoJT3BlcmF0aW9uEgcKA0FkZBAAEgcKA01v",
            "ZBABEgcKA0RlbBACEgcKA0dldBADQhiqAhVMZW1vbmFkZS5OZXQuUHJvdG9j",
            "b2xiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Lemonade.Net.Protocol.Operation), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum Operation {
    [pbr::OriginalName("Add")] Add = 0,
    [pbr::OriginalName("Mod")] Mod = 1,
    [pbr::OriginalName("Del")] Del = 2,
    [pbr::OriginalName("Get")] Get = 3,
  }

  #endregion

}

#endregion Designer generated code
