// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TrialAvatarGrantRecord.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Lemonade.Net.Protocol {

  /// <summary>Holder for reflection information generated from TrialAvatarGrantRecord.proto</summary>
  public static partial class TrialAvatarGrantRecordReflection {

    #region Descriptor
    /// <summary>File descriptor for TrialAvatarGrantRecord.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TrialAvatarGrantRecordReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxUcmlhbEF2YXRhckdyYW50UmVjb3JkLnByb3RvIocCChZUcmlhbEF2YXRh",
            "ckdyYW50UmVjb3JkEhQKDGdyYW50X3JlYXNvbhgBIAEoDRIcChRmcm9tX3Bh",
            "cmVudF9xdWVzdF9pZBgCIAEoDSK4AQoLR3JhbnRSZWFzb24SCwoHSU5WQUxJ",
            "RBAAEhIKDkdSQU5UX0JZX1FVRVNUEAESIgoeR1JBTlRfQllfVFJJQUxfQVZB",
            "VEFSX0FDVElWSVRZEAISJgoiR1JBTlRfQllfRFVOR0VPTl9FTEVNRU5UX0NI",
            "QUxMRU5HRRADEiAKHEdSQU5UX0JZX01JU1RfVFJJQUxfQUNUSVZJVFkQBBIa",
            "ChZHUkFOVF9CWV9TVU1PX0FDVElWSVRZEAVCGKoCFUxlbW9uYWRlLk5ldC5Q",
            "cm90b2NvbGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Lemonade.Net.Protocol.TrialAvatarGrantRecord), global::Lemonade.Net.Protocol.TrialAvatarGrantRecord.Parser, new[]{ "GrantReason", "FromParentQuestId" }, null, new[]{ typeof(global::Lemonade.Net.Protocol.TrialAvatarGrantRecord.Types.GrantReason) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class TrialAvatarGrantRecord : pb::IMessage<TrialAvatarGrantRecord>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TrialAvatarGrantRecord> _parser = new pb::MessageParser<TrialAvatarGrantRecord>(() => new TrialAvatarGrantRecord());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TrialAvatarGrantRecord> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Lemonade.Net.Protocol.TrialAvatarGrantRecordReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrialAvatarGrantRecord() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrialAvatarGrantRecord(TrialAvatarGrantRecord other) : this() {
      grantReason_ = other.grantReason_;
      fromParentQuestId_ = other.fromParentQuestId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrialAvatarGrantRecord Clone() {
      return new TrialAvatarGrantRecord(this);
    }

    /// <summary>Field number for the "grant_reason" field.</summary>
    public const int GrantReasonFieldNumber = 1;
    private uint grantReason_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint GrantReason {
      get { return grantReason_; }
      set {
        grantReason_ = value;
      }
    }

    /// <summary>Field number for the "from_parent_quest_id" field.</summary>
    public const int FromParentQuestIdFieldNumber = 2;
    private uint fromParentQuestId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FromParentQuestId {
      get { return fromParentQuestId_; }
      set {
        fromParentQuestId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TrialAvatarGrantRecord);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TrialAvatarGrantRecord other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GrantReason != other.GrantReason) return false;
      if (FromParentQuestId != other.FromParentQuestId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (GrantReason != 0) hash ^= GrantReason.GetHashCode();
      if (FromParentQuestId != 0) hash ^= FromParentQuestId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (GrantReason != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(GrantReason);
      }
      if (FromParentQuestId != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(FromParentQuestId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (GrantReason != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(GrantReason);
      }
      if (FromParentQuestId != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(FromParentQuestId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (GrantReason != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GrantReason);
      }
      if (FromParentQuestId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FromParentQuestId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TrialAvatarGrantRecord other) {
      if (other == null) {
        return;
      }
      if (other.GrantReason != 0) {
        GrantReason = other.GrantReason;
      }
      if (other.FromParentQuestId != 0) {
        FromParentQuestId = other.FromParentQuestId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            GrantReason = input.ReadUInt32();
            break;
          }
          case 16: {
            FromParentQuestId = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            GrantReason = input.ReadUInt32();
            break;
          }
          case 16: {
            FromParentQuestId = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the TrialAvatarGrantRecord message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum GrantReason {
        [pbr::OriginalName("INVALID")] Invalid = 0,
        [pbr::OriginalName("GRANT_BY_QUEST")] GrantByQuest = 1,
        [pbr::OriginalName("GRANT_BY_TRIAL_AVATAR_ACTIVITY")] GrantByTrialAvatarActivity = 2,
        [pbr::OriginalName("GRANT_BY_DUNGEON_ELEMENT_CHALLENGE")] GrantByDungeonElementChallenge = 3,
        [pbr::OriginalName("GRANT_BY_MIST_TRIAL_ACTIVITY")] GrantByMistTrialActivity = 4,
        [pbr::OriginalName("GRANT_BY_SUMO_ACTIVITY")] GrantBySumoActivity = 5,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
