// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: VisionType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Lemonade.Net.Protocol {

  /// <summary>Holder for reflection information generated from VisionType.proto</summary>
  public static partial class VisionTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for VisionType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static VisionTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBWaXNpb25UeXBlLnByb3RvKqwDCgpWaXNpb25UeXBlEg8KC1ZJU0lPTl9O",
            "T05FEAASDwoLVklTSU9OX01FRVQQARIRCg1WSVNJT05fUkVCT1JOEAISEgoO",
            "VklTSU9OX1JFUExBQ0UQAxIaChZWSVNJT05fV0FZUE9JTlRfUkVCT1JOEAQS",
            "DwoLVklTSU9OX01JU1MQBRIOCgpWSVNJT05fRElFEAYSGAoUVklTSU9OX0dB",
            "VEhFUl9FU0NBUEUQBxISCg5WSVNJT05fUkVGUkVTSBAIEhQKEFZJU0lPTl9U",
            "UkFOU1BPUlQQCRIWChJWSVNJT05fUkVQTEFDRV9ESUUQChIcChhWSVNJT05f",
            "UkVQTEFDRV9OT19OT1RJRlkQCxIPCgtWSVNJT05fQk9SThAMEhEKDVZJU0lP",
            "Tl9QSUNLVVAQDRIRCg1WSVNJT05fUkVNT1ZFEA4SGQoVVklTSU9OX0NIQU5H",
            "RV9DT1NUVU1FEA8SFwoTVklTSU9OX0ZJU0hfUkVGUkVTSBAQEhkKFVZJU0lP",
            "Tl9GSVNIX0JJR19TSE9DSxAREhgKFFZJU0lPTl9GSVNIX1FURV9TVUNDEBJC",
            "GKoCFUxlbW9uYWRlLk5ldC5Qcm90b2NvbGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Lemonade.Net.Protocol.VisionType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum VisionType {
    [pbr::OriginalName("VISION_NONE")] VisionNone = 0,
    [pbr::OriginalName("VISION_MEET")] VisionMeet = 1,
    [pbr::OriginalName("VISION_REBORN")] VisionReborn = 2,
    [pbr::OriginalName("VISION_REPLACE")] VisionReplace = 3,
    [pbr::OriginalName("VISION_WAYPOINT_REBORN")] VisionWaypointReborn = 4,
    [pbr::OriginalName("VISION_MISS")] VisionMiss = 5,
    [pbr::OriginalName("VISION_DIE")] VisionDie = 6,
    [pbr::OriginalName("VISION_GATHER_ESCAPE")] VisionGatherEscape = 7,
    [pbr::OriginalName("VISION_REFRESH")] VisionRefresh = 8,
    [pbr::OriginalName("VISION_TRANSPORT")] VisionTransport = 9,
    [pbr::OriginalName("VISION_REPLACE_DIE")] VisionReplaceDie = 10,
    [pbr::OriginalName("VISION_REPLACE_NO_NOTIFY")] VisionReplaceNoNotify = 11,
    [pbr::OriginalName("VISION_BORN")] VisionBorn = 12,
    [pbr::OriginalName("VISION_PICKUP")] VisionPickup = 13,
    [pbr::OriginalName("VISION_REMOVE")] VisionRemove = 14,
    [pbr::OriginalName("VISION_CHANGE_COSTUME")] VisionChangeCostume = 15,
    [pbr::OriginalName("VISION_FISH_REFRESH")] VisionFishRefresh = 16,
    [pbr::OriginalName("VISION_FISH_BIG_SHOCK")] VisionFishBigShock = 17,
    [pbr::OriginalName("VISION_FISH_QTE_SUCC")] VisionFishQteSucc = 18,
  }

  #endregion

}

#endregion Designer generated code
